modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="frequency"
version="${version}"
displayName="Frequency for Create"
displayURL="https://github.com/MaliceZed"
logoFile="logo.png"
credits="Create mod"
authors="MaZe"
description="Frequency for Create is a quality-of-life addon for the Create mod that adds a set of symbol items for configuring Redstone Link frequencies."
enumExtensions="META-INF/enumextensions.json"

[[dependencies.frequency]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.frequency]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.frequency]]
    modId="create"
    type="required"
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="frequency.mixins.json"