package maze.frequency.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;

import net.minecraft.world.item.Item;

import maze.frequency.item.*;
import maze.frequency.FrequencyMod;

public class FrequencyModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(FrequencyMod.MODID);
	public static final DeferredItem<Item> SYMBOL_EMPTY;
	public static final DeferredItem<Item> SYMBOL_0;
	public static final DeferredItem<Item> SYMBOL_1;
	public static final DeferredItem<Item> SYMBOL_2;
	public static final DeferredItem<Item> SYMBOL_3;
	public static final DeferredItem<Item> SYMBOL_4;
	public static final DeferredItem<Item> SYMBOL_5;
	public static final DeferredItem<Item> SYMBOL_6;
	public static final DeferredItem<Item> SYMBOL_7;
	public static final DeferredItem<Item> SYMBOL_8;
	public static final DeferredItem<Item> SYMBOL_9;
	public static final DeferredItem<Item> SYMBOL_A;
	public static final DeferredItem<Item> SYMBOL_B;
	public static final DeferredItem<Item> SYMBOL_C;
	public static final DeferredItem<Item> SYMBOL_D;
	public static final DeferredItem<Item> SYMBOL_E;
	public static final DeferredItem<Item> SYMBOL_F;
	public static final DeferredItem<Item> SYMBOL_G;
	public static final DeferredItem<Item> SYMBOL_H;
	public static final DeferredItem<Item> SYMBOL_I;
	public static final DeferredItem<Item> SYMBOL_J;
	public static final DeferredItem<Item> SYMBOL_K;
	public static final DeferredItem<Item> SYMBOL_L;
	public static final DeferredItem<Item> SYMBOL_M;
	public static final DeferredItem<Item> SYMBOL_N;
	public static final DeferredItem<Item> SYMBOL_O;
	public static final DeferredItem<Item> SYMBOL_P;
	public static final DeferredItem<Item> SYMBOL_Q;
	public static final DeferredItem<Item> SYMBOL_R;
	public static final DeferredItem<Item> SYMBOL_S;
	public static final DeferredItem<Item> SYMBOL_T;
	public static final DeferredItem<Item> SYMBOL_U;
	public static final DeferredItem<Item> SYMBOL_V;
	public static final DeferredItem<Item> SYMBOL_W;
	public static final DeferredItem<Item> SYMBOL_X;
	public static final DeferredItem<Item> SYMBOL_Y;
	public static final DeferredItem<Item> SYMBOL_Z;
	public static final DeferredItem<Item> SYMBOL_UP_ARROW;
	public static final DeferredItem<Item> SYMBOL_DOWN_ARROW;
	public static final DeferredItem<Item> SYMBOL_LEFT_ARROW;
	public static final DeferredItem<Item> SYMBOL_RIGHT_ARROW;
	public static final DeferredItem<Item> SYMBOL_DARROW_UP;
	public static final DeferredItem<Item> SYMBOL_DARROW_DOWN;
	public static final DeferredItem<Item> SYMBOL_DARROW_LEFT;
	public static final DeferredItem<Item> SYMBOL_DARROW_RIGHT;
	public static final DeferredItem<Item> INCOMPLETE_SYMBOL;
	static {
		SYMBOL_EMPTY = REGISTRY.register("symbol_empty", SymbolEmptyItem::new);
		SYMBOL_0 = REGISTRY.register("symbol_0", Symbol0Item::new);
		SYMBOL_1 = REGISTRY.register("symbol_1", Symbol1Item::new);
		SYMBOL_2 = REGISTRY.register("symbol_2", Symbol2Item::new);
		SYMBOL_3 = REGISTRY.register("symbol_3", Symbol3Item::new);
		SYMBOL_4 = REGISTRY.register("symbol_4", Symbol4Item::new);
		SYMBOL_5 = REGISTRY.register("symbol_5", Symbol5Item::new);
		SYMBOL_6 = REGISTRY.register("symbol_6", Symbol6Item::new);
		SYMBOL_7 = REGISTRY.register("symbol_7", Symbol7Item::new);
		SYMBOL_8 = REGISTRY.register("symbol_8", Symbol8Item::new);
		SYMBOL_9 = REGISTRY.register("symbol_9", Symbol9Item::new);
		SYMBOL_A = REGISTRY.register("symbol_a", SymbolAItem::new);
		SYMBOL_B = REGISTRY.register("symbol_b", SymbolBItem::new);
		SYMBOL_C = REGISTRY.register("symbol_c", SymbolCItem::new);
		SYMBOL_D = REGISTRY.register("symbol_d", SymbolDItem::new);
		SYMBOL_E = REGISTRY.register("symbol_e", SymbolEItem::new);
		SYMBOL_F = REGISTRY.register("symbol_f", SymbolFItem::new);
		SYMBOL_G = REGISTRY.register("symbol_g", SymbolGItem::new);
		SYMBOL_H = REGISTRY.register("symbol_h", SymbolHItem::new);
		SYMBOL_I = REGISTRY.register("symbol_i", SymbolIItem::new);
		SYMBOL_J = REGISTRY.register("symbol_j", SymbolJItem::new);
		SYMBOL_K = REGISTRY.register("symbol_k", SymbolKItem::new);
		SYMBOL_L = REGISTRY.register("symbol_l", SymbolLItem::new);
		SYMBOL_M = REGISTRY.register("symbol_m", SymbolMItem::new);
		SYMBOL_N = REGISTRY.register("symbol_n", SymbolNItem::new);
		SYMBOL_O = REGISTRY.register("symbol_o", SymbolOItem::new);
		SYMBOL_P = REGISTRY.register("symbol_p", SymbolPItem::new);
		SYMBOL_Q = REGISTRY.register("symbol_q", SymbolQItem::new);
		SYMBOL_R = REGISTRY.register("symbol_r", SymbolRItem::new);
		SYMBOL_S = REGISTRY.register("symbol_s", SymbolSItem::new);
		SYMBOL_T = REGISTRY.register("symbol_t", SymbolTItem::new);
		SYMBOL_U = REGISTRY.register("symbol_u", SymbolUItem::new);
		SYMBOL_V = REGISTRY.register("symbol_v", SymbolVItem::new);
		SYMBOL_W = REGISTRY.register("symbol_w", SymbolWItem::new);
		SYMBOL_X = REGISTRY.register("symbol_x", SymbolXItem::new);
		SYMBOL_Y = REGISTRY.register("symbol_y", SymbolYItem::new);
		SYMBOL_Z = REGISTRY.register("symbol_z", SymbolZItem::new);
		SYMBOL_UP_ARROW = REGISTRY.register("symbol_up_arrow", SymbolUpArrowItem::new);
		SYMBOL_DOWN_ARROW = REGISTRY.register("symbol_down_arrow", SymbolDownArrowItem::new);
		SYMBOL_LEFT_ARROW = REGISTRY.register("symbol_left_arrow", SymbolLeftArrowItem::new);
		SYMBOL_RIGHT_ARROW = REGISTRY.register("symbol_right_arrow", SymbolRightArrowItem::new);
		SYMBOL_DARROW_UP = REGISTRY.register("symbol_darrow_up", SymbolDarrowUpItem::new);
		SYMBOL_DARROW_DOWN = REGISTRY.register("symbol_darrow_down", SymbolDarrowDownItem::new);
		SYMBOL_DARROW_LEFT = REGISTRY.register("symbol_darrow_left", SymbolDarrowLeftItem::new);
		SYMBOL_DARROW_RIGHT = REGISTRY.register("symbol_darrow_right", SymbolDarrowRightItem::new);
		INCOMPLETE_SYMBOL = REGISTRY.register("incomplete_symbol", IncompleteSymbolItem::new);
	}
}
