plugins {
    id 'java-library'
}

archivesBaseName = "${project.mod_id}-common-${project.minecraft_version}"

// Disable compilation tasks for common module
// Common code is compiled by loader-specific modules
tasks.withType(JavaCompile).configureEach {
    enabled = false
}

tasks.named('jar') {
    enabled = false
}

java {
    withSourcesJar()
}
